server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:al3xliu/spring-cloud-config.git"

  application:
    name: configserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
