server:
  port: 5678
spring:
  application:
    name: sidecar
sidecar:
  port: 9081
  health-uri: http://localhost:9081/health.json
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
